Repository HyeranJo/bookbuddy, pull requests merged in 2023-09, with the labels that each got.

#21 Feat fe/searchpage
  client/src/api/GetApi.ts
  client/src/api/PostApi.ts
  client/src/components/header/Header.tsx
  client/src/components/search/SearchBar.style.ts
  client/src/components/search/SearchBar.tsx
  client/src/components/table/FAQ.style.ts
  client/src/pages/bookdetail/Bookdetail.tsx
  client/src/pages/customer/Customer.style.ts
  client/src/pages/customer/Customer.tsx
  client/src/pages/list/List.tsx
  client/src/pages/search/Search.style.ts
  client/src/pages/search/Search.tsx
  client/src/recoil/SearchValue.ts
Labels: fe, Feat, fix

#22 Feat fe/searchpage
  client/src/components/search/SearchBar.tsx
  client/src/pages/sign/Signup.tsx
Labels: Feat, fix

#25 Feat fe/fix
  client/src/components/book/Book.tsx
  client/src/components/info_nav/InfoNav.tsx
  client/src/components/search/SearchBar.style.ts
  client/src/components/search/SearchBar.tsx
  client/src/pages/bookdetail/Bookdetail.tsx
  client/src/pages/list/List.tsx
  client/src/pages/search/Search.style.ts
  client/src/pages/search/Search.tsx
  client/src/pages/sign/Signin.tsx
Labels: fe, fix

#27 Feat fe/bookmark
  client/src/api/GetApi.ts
  client/src/components/book/Book.tsx
  client/src/index.tsx
  client/src/model/BookList.ts
  client/src/pages/mypage/Mypage.style.ts
  client/src/pages/mypage/Mypage.tsx
  client/src/pages/sign/Signin.tsx
Labels: fe, Feat

#29 Dev be
  server/build.gradle
  server/src/main/java/com/bookbuddy/demo/book/controller/BookController.java
  server/src/main/java/com/bookbuddy/demo/book/dto/BookDto.java
  server/src/main/java/com/bookbuddy/demo/book/entity/Book.java
  server/src/main/java/com/bookbuddy/demo/book/mapper/BookMapper.java
  server/src/main/java/com/bookbuddy/demo/book/repository/BookRepository.java
  server/src/main/java/com/bookbuddy/demo/book/service/BookService.java
  server/src/main/java/com/bookbuddy/demo/bookmark/controller/BookmarkController.java
  server/src/main/java/com/bookbuddy/demo/bookmark/dto/BookmarkDto.java
  server/src/main/java/com/bookbuddy/demo/bookmark/entity/Bookmark.java
  server/src/main/java/com/bookbuddy/demo/bookmark/mapper/BookmarkMapper.java
  server/src/main/java/com/bookbuddy/demo/bookmark/repository/BookmarkRepository.java
  server/src/main/java/com/bookbuddy/demo/bookmark/service/BookmarkService.java
  server/src/main/java/com/bookbuddy/demo/category/controller/CategoryController.java
  server/src/main/java/com/bookbuddy/demo/category/dto/CategoryDto.java
  server/src/main/java/com/bookbuddy/demo/category/entity/Category.java
  server/src/main/java/com/bookbuddy/demo/category/mapper/CategoryMapper.java
  server/src/main/java/com/bookbuddy/demo/category/repository/CategoryRepository.java
  server/src/main/java/com/bookbuddy/demo/category/service/CategoryService.java
  server/src/main/java/com/bookbuddy/demo/global/controller/CrawlingController.java
  server/src/main/java/com/bookbuddy/demo/global/controller/SearchController.java
  server/src/main/java/com/bookbuddy/demo/global/crawling/CrawlingService.java
  server/src/main/java/com/bookbuddy/demo/global/dto/LoginDto.java
  server/src/main/java/com/bookbuddy/demo/global/dto/PageInfo.java
  server/src/main/java/com/bookbuddy/demo/global/dto/SearchDto.java
  server/src/main/java/com/bookbuddy/demo/global/dto/response/LoginResponseDto.java
  server/src/main/java/com/bookbuddy/demo/global/dto/response/MultiResponseDto.java
  server/src/main/java/com/bookbuddy/demo/global/dto/response/SingleResponseDto.java
  server/src/main/java/com/bookbuddy/demo/global/exception/BusinessException.java
  server/src/main/java/com/bookbuddy/demo/global/exception/ExceptionCode.java
  server/src/main/java/com/bookbuddy/demo/global/security/CustomUserDetailsService.java
  server/src/main/java/com/bookbuddy/demo/global/security/MemberDetails.java
  server/src/main/java/com/bookbuddy/demo/global/security/config/SecurityConfig.java
  server/src/main/java/com/bookbuddy/demo/global/security/jwt/JwtAuthenticationFilter.java
  server/src/main/java/com/bookbuddy/demo/global/security/jwt/JwtTokenizer.java
  server/src/main/java/com/bookbuddy/demo/global/security/jwt/JwtVerifyFilter.java
  server/src/main/java/com/bookbuddy/demo/main/MainController.java
  server/src/main/java/com/bookbuddy/demo/member/controller/MemberController.java
  server/src/main/java/com/bookbuddy/demo/member/dto/MemberDto.java
  server/src/main/java/com/bookbuddy/demo/member/entity/Member.java
  server/src/main/java/com/bookbuddy/demo/member/entity/MemberEmail.java
  server/src/main/java/com/bookbuddy/demo/member/mapper/MemberMapper.java
  server/src/main/java/com/bookbuddy/demo/member/repository/MemberRepository.java
  server/src/main/java/com/bookbuddy/demo/member/service/MemberService.java
  server/src/main/java/com/bookbuddy/demo/member/service/MemberServiceImpl.java
  server/src/main/java/com/bookbuddy/demo/order/controller/OrderController.java
  server/src/main/java/com/bookbuddy/demo/order/dto/OrderDto.java
  server/src/main/java/com/bookbuddy/demo/order/entity/Order.java
  server/src/main/java/com/bookbuddy/demo/order/mapper/OrderMapper.java
  server/src/main/java/com/bookbuddy/demo/order/repository/OrderRepository.java
  server/src/main/java/com/bookbuddy/demo/order/service/OrderService.java
  server/src/main/java/com/bookbuddy/demo/payment/controller/PaymentController.java
  server/src/main/java/com/bookbuddy/demo/payment/dto/PaymentDto.java
  server/src/main/java/com/bookbuddy/demo/payment/entity/Payment.java
  server/src/main/java/com/bookbuddy/demo/payment/mapper/PaymentMapper.java
  server/src/main/java/com/bookbuddy/demo/payment/repository/PaymentRepository.java
  server/src/main/java/com/bookbuddy/demo/payment/service/PaymentService.java
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
Labels: be

#30 Feat: aws rds와 mysql 연결
  server/build.gradle
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
Labels: be

#32 Feat fe/fix
  client/src/components/book/Book.tsx
  client/src/pages/sign/Signin.tsx
Labels: Feat, fix

#36 Dev be
  server/src/main/java/com/bookbuddy/demo/board/controller/BoardController.java
  server/src/main/java/com/bookbuddy/demo/board/dto/BoardDto.java
  server/src/main/java/com/bookbuddy/demo/board/entity/Board.java
  server/src/main/java/com/bookbuddy/demo/board/mapper/BoardMapper.java
  server/src/main/java/com/bookbuddy/demo/board/repository/BoardRepository.java
  server/src/main/java/com/bookbuddy/demo/board/service/BoardService.java
  server/src/main/java/com/bookbuddy/demo/book/controller/BookController.java
  server/src/main/java/com/bookbuddy/demo/book/entity/Book.java
  server/src/main/java/com/bookbuddy/demo/book/repository/BookRepository.java
  server/src/main/java/com/bookbuddy/demo/book/service/BookService.java
  server/src/main/java/com/bookbuddy/demo/bookmark/service/BookmarkService.java
  server/src/main/java/com/bookbuddy/demo/global/exception/ExceptionCode.java
  server/src/main/java/com/bookbuddy/demo/global/security/config/SecurityConfig.java
  server/src/main/java/com/bookbuddy/demo/member/entity/Member.java
  server/src/main/java/com/bookbuddy/demo/order/controller/OrderController.java
  server/src/main/resources/application-server.yml
Labels: be

#40 Dev be
  server/src/main/java/com/bookbuddy/demo/book/entity/Book.java
  server/src/main/java/com/bookbuddy/demo/cart/controller/CartController.java
  server/src/main/java/com/bookbuddy/demo/cart/dto/CartDto.java
  server/src/main/java/com/bookbuddy/demo/cart/entity/Cart.java
  server/src/main/java/com/bookbuddy/demo/cart/mapper/CartMapper.java
  server/src/main/java/com/bookbuddy/demo/cart/repository/CartRepository.java
  server/src/main/java/com/bookbuddy/demo/cart/service/CartService.java
  server/src/main/java/com/bookbuddy/demo/global/dto/response/MultiResponseDto.java
  server/src/main/java/com/bookbuddy/demo/global/exception/ExceptionCode.java
  server/src/main/java/com/bookbuddy/demo/global/security/config/SecurityConfig.java
  server/src/main/java/com/bookbuddy/demo/member/entity/Member.java
  server/src/main/java/com/bookbuddy/demo/order/controller/OrderController.java
  server/src/main/java/com/bookbuddy/demo/order/dto/OrderDto.java
  server/src/main/java/com/bookbuddy/demo/order/entity/Order.java
  server/src/main/java/com/bookbuddy/demo/order/mapper/OrderMapper.java
  server/src/main/java/com/bookbuddy/demo/order/repository/OrderRepository.java
  server/src/main/java/com/bookbuddy/demo/order/service/OrderService.java
  server/src/main/java/com/bookbuddy/demo/orderbook/OrderBook.java
  server/src/main/java/com/bookbuddy/demo/orderbook/OrderBookDto.java
  server/src/main/java/com/bookbuddy/demo/payment/controller/PaymentController.java
  server/src/main/java/com/bookbuddy/demo/payment/dto/PaymentDto.java
  server/src/main/java/com/bookbuddy/demo/payment/entity/Payment.java
  server/src/main/java/com/bookbuddy/demo/payment/mapper/PaymentMapper.java
  server/src/main/java/com/bookbuddy/demo/payment/repository/PaymentRepository.java
  server/src/main/java/com/bookbuddy/demo/payment/service/PaymentService.java
  server/src/main/resources/application-server.yml
Labels: be

#46 Feat fe/fixsearch
  client/src/api/GetApi.ts
  client/src/pages/customer/Customer.style.ts
  client/src/pages/search/Search.style.ts
  client/src/pages/search/Search.tsx
Labels: fe, fix

#54 Update README.md
  README.md
Labels: documentation

#68 Dev be
  server/src/main/java/com/bookbuddy/demo/book/entity/Book.java
  server/src/main/java/com/bookbuddy/demo/global/exception/ExceptionCode.java
  server/src/main/java/com/bookbuddy/demo/member/entity/Member.java
  server/src/test/java/com/bookbuddy/demo/bookmark/service/BookmarkServiceTest.java
Labels: be
